<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" id="boxLogin" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email OR Mobile')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               id="email" type="text" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email OR Mobile')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password"
                            <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass"
                               title="<?= $block->escapeHtmlAttr(__('Password')) ?>"/>
                    </div>
                </div>
                <div class="field choice" data-bind="scope: 'showPassword'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"  style="display: none" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="secondary">
                        <button type="button"
                                style="display: none"
                                class="action login secondary" name="sendOtp" id="sendOtp">
                            <span><?= $block->escapeHtml(__('Sign in With OTP')) ?></span>
                        </button></div>

                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>
                </div>
            </fieldset>
            <fieldset class="fieldset auth" style="display: none" id="boxAuth" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('Submit Auth Code.')) ?></div>
                <input name="login[authCode]"
                       value="<?= $block->escapeHtmlAttr($block->getAuthCode()) ?>"
                       id="authCode" type="number"
                       class="input-text"
                       title="<?= $block->escapeHtmlAttr(__('Auth Code')) ?>"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true}">
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit"
                                style="margin-top: 5px"
                                class="action login primary"
                                name="send" id="send3">
                            <span><?= $block->escapeHtml(__('Sign In')) ?></span>
                        </button>
                    </div>
                </div>
            </fieldset>

        </form>
    </div>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "login-form"
                },
                "Magento_Ui/js/core/app": {
                    "components": {
                        "showPassword": {
                            "component": "Magento_Customer/js/show-password",
                            "passwordSelector": "#pass"
                        }
                    }
                },
                "Magesoft_Otp/js/opt-login": {
                    "usernameInputSelector":"#email",
                    "btnOtpSelector": "#sendOtp",
                    "signInSelector":"#send2",
                    "passwordInputSelector": "#pass",
                    "boxLoginSelector":"#boxLogin",
                    "boxAuthSelector":"#boxAuth",
                    "expireTime":2,
                    "ajaxUrl":"<?= $block->getSendCodeUrl()?>",
                    "ajaxUrlCheck":"<?= $block->getCheckCodeUrl()?>",
                    "btnSingAuth":"#send3",
                    "authCodeInput":"#authCode"
                }
            }
        }
    </script>
</div>
